# Generated by Django 2.0.3 on 2018-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180330_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
