# Generated by Django 2.0.3 on 2018-03-30 13:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolistitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='contact',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='photo',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
